/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 471224fbb1c2609d32d4fed6240d63f9)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ForeverChatAgent";
  }
  interface Env {
    AI: Ai;
    OPENAI_API_KEY: string;
    ANTHROPIC_API_KEY: string;
    INFERENCE_BUFFER: Fetcher;
    ForeverChatAgent: DurableObjectNamespace<
      import("./src/server").ForeverChatAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY" | "ANTHROPIC_API_KEY">
  > {}
}
