/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 434e7ddc28a991b7e3366a3daf6796c2)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "TaskAgent";
  }
  interface Env {
    TaskAgent: DurableObjectNamespace<import("./src/server").TaskAgent>;
    TASK_WORKFLOW: Workflow<
      Parameters<
        import("./src/server").TaskProcessingWorkflow["run"]
      >[0]["payload"]
    >;
  }
}
interface Env extends Cloudflare.Env {}
