/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 3b0868993189c509ce2a638b2579e43e)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyMCP";
  }
  interface Env {}
}
interface Env extends Cloudflare.Env {}
