/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 9b9b5725c2e3a632d3482e7cec03aa70)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ResumableStreamingChat";
  }
  interface Env {
    AI: Ai;
    OPENAI_API_KEY: string;
    ResumableStreamingChat: DurableObjectNamespace<
      import("./src/server").ResumableStreamingChat
    >;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY">
  > {}
}
