/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e33a48f2f38c03cef62c765d5b20fe51)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyAssistant";
  }
  interface Env {
    LOADER: WorkerLoader;
    AI: Ai;
    MyAssistant: DurableObjectNamespace<import("./src/server").MyAssistant>;
  }
}
interface Env extends Cloudflare.Env {}
