/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e95c326b45fb19c0ccf4ebc53ec48c0e)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyAgent";
  }
  interface Env {
    OPENAI_API_KEY: string;
    MyAgent: DurableObjectNamespace<import("./src/server").MyAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY">
  > {}
}
