/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 80596049446076b5f33e34fc90c973f9)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
  }
  interface Env {
    AI: Ai;
    VoiceInputAgent: DurableObjectNamespace<
      import("./src/server").VoiceInputAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
