/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 77f83f36b39c2a5d710f72f88d2fd70c)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "WorkspaceChatAgent";
  }
  interface Env {
    LOADER: WorkerLoader;
    AI: Ai;
    WorkspaceChatAgent: DurableObjectNamespace<
      import("./src/server").WorkspaceChatAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
