/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: a0e77abbdf6f66909ab85b483f586e3a)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyVoiceAgent";
  }
  interface Env {
    AI: Ai;
    ELEVENLABS_API_KEY: string;
    CLOUDFLARE_REALTIME_SFU_APP_ID: string;
    CLOUDFLARE_REALTIME_SFU_API_TOKEN: string;
    MyVoiceAgent: DurableObjectNamespace<import("./src/server").MyVoiceAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ELEVENLABS_API_KEY"
      | "CLOUDFLARE_REALTIME_SFU_APP_ID"
      | "CLOUDFLARE_REALTIME_SFU_API_TOKEN"
    >
  > {}
}
