/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 926ba50529f4a9eff59409bd1dc88cd8)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "MyAgent";
  }
  interface Env {
    MyAgent: DurableObjectNamespace<import("./src/index").MyAgent>;
  }
}
interface Env extends Cloudflare.Env {}
