/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false --strict-vars false`
declare namespace Cloudflare {
  interface Env {
    OPENAI_API_KEY: string;
    MyAgent: DurableObjectNamespace<import("./src/server").MyAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY">
  > {}
}
