/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 5130d59e868fde56585b9bc2d00e2461)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "HumanInTheLoop";
  }
  interface Env {
    AI: Ai;
    OPENAI_API_KEY: string;
    AI_GATEWAY_TOKEN: string;
    HumanInTheLoop: DurableObjectNamespace<
      import("./src/server").HumanInTheLoop
    >;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY" | "AI_GATEWAY_TOKEN">
  > {}
}
