/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 8f9c651072ec4f30c93c6c12a7aedf3f)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "ChessGame";
  }
  interface Env {
    CHESS: DurableObjectNamespace<import("./src/index").ChessGame>;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
