/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 4b7d53fb40f24642b2ec6c5818c5da3a)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "StructuredInputAgent";
  }
  interface Env {
    AI: Ai;
    StructuredInputAgent: DurableObjectNamespace<
      import("./src/server").StructuredInputAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
