/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 1f40cce47f4050ba5e4f6846656ad464)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "InferenceBuffer";
  }
  interface Env {
    AI: Ai;
    INFERENCE_BUFFER: DurableObjectNamespace<
      import("./src/index").InferenceBuffer
    >;
  }
}
interface Env extends Cloudflare.Env {}
