/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: edc8e1c6bad145a3debaf469cac38b55)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyAgent";
  }
  interface Env {
    MyAgent: DurableObjectNamespace<import("./src/server").MyAgent>;
  }
}
interface Env extends Cloudflare.Env {}
