/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 4672324705317fee9bdf53a10d65cdb2)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "TicTacToe";
  }
  interface Env {
    OPENAI_API_KEY: string;
    TicTacToe: DurableObjectNamespace<import("./src/server").TicTacToe>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY">
  > {}
}
