/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "WorkerPlayground";
  }
  interface Env {
    AI: Ai;
    LOADER: WorkerLoader;
    WorkerPlayground: DurableObjectNamespace<
      import("./src/server").WorkerPlayground
    >;
  }
}
interface Env extends Cloudflare.Env {}
