/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 80d06c1c296fe7f1d2c31fc935f78abe)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces:
      | "VoiceChatAgent"
      | "SoundscapeAgent"
      | "CharacterAgent"
      | "MusicAgent";
  }
  interface Env {
    AUDIO_BUCKET: R2Bucket;
    AI: Ai;
    ELEVENLABS_API_KEY: string;
    VoiceChatAgent: DurableObjectNamespace<
      import("./src/server").VoiceChatAgent
    >;
    SoundscapeAgent: DurableObjectNamespace<
      import("./src/server").SoundscapeAgent
    >;
    CharacterAgent: DurableObjectNamespace<
      import("./src/server").CharacterAgent
    >;
    MusicAgent: DurableObjectNamespace<import("./src/server").MusicAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ELEVENLABS_API_KEY">
  > {}
}
