/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 83be826bfd14e0006039e186e1b11835)
declare namespace Cloudflare {
  interface Env {
    DOCS_KV: KVNamespace;
  }
}
interface Env extends Cloudflare.Env {}
