/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 33efd3b17229f92f32173efc2e9ad735)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MultiSessionAgent";
  }
  interface Env {
    AI: Ai;
    MultiSessionAgent: DurableObjectNamespace<
      import("./src/server").MultiSessionAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
